config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/show'

  get 'login',   to: 'sessions#new',     as: 'login'
  get 'signup',  to: 'users#new',        as: 'signup'
  get 'logout',  to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :users do
    resources :activities
    resources :milestones, :except => :show
    resources :goals, :except => :show do
      get 'starting_point'
      post 'starting_point' => 'milestones#starting_point'
    end
  end

  root 'dashboard#show'

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base

  belongs_to :type
  belongs_to :user

  validates :type, presence: true
  validates :user, presence: true
  validates :value, presence: true

  scope :for_user, ->(user) { where(user: user) }

  def value
    v = read_attribute(:value)
    if self.type and self.type.name == 'weight'
      v = v.to_f / 1000.0
    end
    return v
  end

  def value=(value)
    if self.type and self.type.name == 'weight'
      value = value.to_f * 1000.0
    end
    write_attribute(:value, value.to_i)
  end

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController

  before_action :check_permission
  before_action :set_user
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]

  # GET /milestones
  def index
    @goals_by_type = Goal.for_user(current_user).each_with_object({}) do |goal, h|
      h.merge!({ goal.type.id => goal })
    end
    @milestones = Milestone.for_user(current_user).order('achieved_at DESC, created_at DESC').all
  end

  # GET /milestones/1
  def show
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
    @milestone.achieved_at = Date.today
  end

  # GET /milestones/1/edit
  def edit
  end

  def starting_point
    @goal = Goal.find(params[:goal_id])
    if milestone_params[:id].blank?
      @milestone = Milestone.new(milestone_params)
      @milestone.user = @user
    else
      @milestone = Milestone.find(milestone_params[:id])
      @milestone.attributes = milestone_params
    end
    @milestone.value = milestone_params[:value]

    if @milestone.save
      redirect_to user_goals_url(@user), notice: 'First milestone was successfully saved.'
    else
      render 'goals/starting_point'
    end
  end

  # POST /milestones
  def create
    @milestone = Milestone.new(milestone_params)
    @milestone.user = @user
    @milestone.value = milestone_params[:value]

    if @milestone.save
      redirect_to user_milestones_url(@user), notice: 'Milestone was successfully created.'
    else
        render :new
    end
  end

  # PATCH/PUT /milestones/1
  def update
    # setting :value after all other attributes because :type is needed to calculate :value
    @milestone.attributes = milestone_params
    @milestone.value = milestone_params[:value]
    if @milestone.save
      redirect_to user_milestones_url(@user), notice: 'Milestone was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /milestones/1
  def destroy
    @milestone.destroy
    redirect_to user_milestones_url(@user), notice: 'Milestone was successfully destroyed.'
  end

  private

    def check_permission
      if !current_user || params[:user_id].to_i != current_user.id.to_i
        render file: 'public/401.html', :status => :unauthorized
      end
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
      @milestone.user = @user
    end

    # Only allow a trusted parameter "white list" through.
    def milestone_params
      params.require(:milestone).permit(:id, :value, :achieved_at, :type_id, :user_id, :is_first)
    end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_form.html.erb
<%= simple_form_for([@user, @milestone], html: { class: 'form-horizontal', role: 'form' }) do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= @milestone.errors.count %> Problem(e) entdeckt:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :type, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.association :type, label: false, input_html: { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :value, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.input :value, :as => :float, label: false, input_html: { class: 'form-control', value: @milestone.try(:value) } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :achieved_at, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.input :achieved_at, label: false, input_html: { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/milestones/edit.html.erb
<h1>Editing milestone</h1>

<%= render 'form' %>

<%= link_to 'Zur Übersicht', user_milestones_path(@user), class: 'btn btn-default' %>

app/views/milestones/index.html.erb
<%= link_to 'Neuer Meilenstein', new_user_milestone_path(@user), class: 'btn btn-primary btn-lg' %><br /><br />

<h1>Meine Meilensteine</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Datum</th>
      <th>Typ</th>
      <th>Wert</th>
      <th style="width: 90px; text-align: center;"></th>
    </tr>
  </thead>

  <tbody>
    <% @milestones.each do |milestone| %>
      <tr>
        <td><%= link_to l(milestone.achieved_at), edit_user_milestone_path(@user, milestone) %></td>
        <td>
          <% if @goals_by_type[milestone.type_id] %>
            <%= @goals_by_type[milestone.type_id] %>
          <% else %>
            <%= milestone.type %>
          <% end %>
        </td>
        <td><%= milestone.value %></td>
        <td style="text-align: center;">
          <%= link_to user_milestone_path(@user, milestone), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/milestones/new.html.erb
<h1>Meilenstein anlegen</h1>

<%= render 'form' %>

<%= link_to 'Zur Übersicht', user_milestones_path(@user), class: 'btn btn-default' %>