config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/show'

  get 'login',   to: 'sessions#new',     as: 'login'
  get 'signup',  to: 'users#new',        as: 'signup'
  get 'logout',  to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :users do
    resources :activities
    resources :milestones, :except => :show
    resources :goals, :except => :show do
      get 'starting_point'
      post 'starting_point' => 'milestones#starting_point'
    end
  end

  root 'dashboard#show'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :type
  belongs_to :user

  validates :type, presence: true
  validates :user, presence: true
  validates :value, presence: true

  scope :for_user, ->(user) { where(user: user) }
  scope :with_first_milestone, -> { includes(:milestone).where('milestones.is_first = 1') }

  def first_milestone
    Milestone.where(is_first: true, type: self.type, user: self.user).first
  end

  def score
    milestones_per_type = Milestone.for_user(self.user).where(type: self.type).order('achieved_at ASC, created_at ASC').all
    return 0.0 if milestones_per_type.blank? or milestones_per_type.size == 0

    first_milestone = milestones_per_type.first
    last_milestone = milestones_per_type.last
    goal_diff = (self.value - first_milestone.send(:value)).abs
    current_diff = (last_milestone.send(:value) - first_milestone.send(:value)).abs
    score = ((current_diff.to_f / goal_diff.to_f) * 100)
    return 0.0 if score < 0.0
    return 100.0 if score > 100.0
    return score
  end

  def value
    value = read_attribute(:value)
    if self.type and self.type.name == 'weight'
      value = value.to_f / 1000.0
    end
    return value
  end

  def value=(value)
    if self.type and self.type.name == 'weight'
      value = value.to_f * 1000.0
    end
    write_attribute(:value, value.to_i)
  end

  def to_s
    return title unless title.blank?
    type
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  include UserPermission, UserDependent

  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  def index
    @goals = Goal.for_user(current_user).all
  end

  # GET /goals/1
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # GET /goals/1/starting_point
  def starting_point
    @goal = Goal.find(params[:goal_id])
    @milestone = Milestone.where(user: current_user).where(type: @goal.type).where(is_first: true).first
    if @milestone.blank?
      @milestone = Milestone.new(user: current_user, type: @goal.type, is_first: true, achieved_at: Date.today)
    end
  end

  # POST /goals
  def create
    @goal = Goal.new(goal_params)
    @goal.user = @user
    @goal.value = goal_params[:value]

    if @goal.save
      redirect_to user_goals_url(@user), notice: 'Goal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /goals/1
  def update
    if @goal.update(goal_params)
      redirect_to user_goals_path(@user), notice: 'Goal was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /goals/1
  def destroy
    @goal.destroy
    redirect_to user_goals_url(@user), notice: 'Goal was successfully destroyed.'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def goal_params
      params.require(:goal).permit(:title, :type_id, :user_id, :value)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= simple_form_for([@user, @goal], html: { class: 'form-horizontal', role: 'form' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.input :title, label: false, input_html: { class: 'form-control' } %>
    </div>
  </div>

  <% if @goal.new_record? %>
    <div class="form-group">
      <%= f.label :type, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.association :type, label: false, input_html: { class: 'form-control' } %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :value, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.input :value, :as => :float, label: false, input_html: { class: 'form-control', value: @goal.try(:value) } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>

<% end %>

app/views/goals/edit.html.erb
<h2>Ziel ändern</h2>

<%= render 'form' %>

<%= link_to 'Zur Übersicht', user_goals_path(@user), class: 'btn btn-default btn-lg' %>

app/views/goals/index.html.erb
<%= link_to 'Neues Ziel', new_user_goal_path(@user), class: 'btn btn-primary btn-lg' %><br /><br />

<h1>Meine Ziele</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Bezeichnung</th>
      <th>Start</th>
      <th>Ziel</th>
      <th style="width: 100px; text-align: center;" nowrap></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <% milestone = goal.first_milestone %>
      <tr>
        <td><%= link_to goal.to_s, edit_user_goal_path(@user, goal) %></td>
        <td><%= "#{milestone.value}" if milestone %></td>
        <td><%= goal.value %></td>
        <td nowrap>
          <%= link_to 'Start', user_goal_starting_point_path(@user, goal), class: 'btn btn-primary' %>
          <%= link_to [@user, goal], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/goals/new.html.erb
<h1>Ziel anlegen</h1>

<%= render 'form' %>

<%= link_to 'Zur Übersicht', user_goals_path(@user), class: 'btn btn-default' %>

app/views/goals/starting_point.html.erb
<%= simple_form_for([@user, @goal, @milestone], url: user_goal_starting_point_path, :method => :post, html: { class: 'form-horizontal', role: 'form' }) do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= @milestone.errors.count %> Problem(e) entdeckt:</h2>

      <ul>
        <% @milestone.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :id, :as => :hidden %>
  <%= f.association :type, :as => :hidden %>
  <%= f.input :is_first, :as => :hidden %>

  <div class="form-group">
    <%= f.label :value, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.input :value, :as => :float, label: false, input_html: { class: 'form-control', value: @milestone.try(:value) } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :achieved_at, 'Gestartet am', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.input :achieved_at, label: false, input_html: { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>