config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/show'

  get 'login',   to: 'sessions#new',     as: 'login'
  get 'signup',  to: 'users#new',        as: 'signup'
  get 'logout',  to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :users do
    resources :activities
    resources :milestones, :except => :show
    resources :goals, :except => :show do
      get 'starting_point'
      post 'starting_point' => 'milestones#starting_point'
    end
  end

  root 'dashboard#show'

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  belongs_to :user

  validates :body, presence: true

  scope :published, -> { where(publish: true) }

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  include UserPermission, UserDependent

  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  def index
    @activities = Activity.where(user: @user).order('created_at DESC').all
  end

  # GET /activities/1
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    @activity.publish = true
    @activity.created_at = Date.today
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  def create
    @activity = Activity.new(activity_params)
    @activity.user = @user

    if @activity.save
      redirect_to [@user, @activity], notice: 'Activity was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /activities/1
  def update
    if @activity.update(activity_params)
      redirect_to [@user, @activity], notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy
    redirect_to user_activities_url(@user), notice: 'Activity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def activity_params
      params.require(:activity).permit(:body, :publish, :created_at)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= simple_form_for([@user, @activity], html: { class: 'form-horizontal activity-form', role: 'form' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.label :body, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.input :body, label: false, input_html: { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :publish, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.input :publish, label: false %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.input :created_at, label: false, :as => :date, input_html: { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group well">
    <div class="col-sm-12">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>

<% end %>

app/views/activities/edit.html.erb
<h2>Aktivität ändern</h2>

<%= render 'form' %>

<%= link_to 'Zur Übersicht', user_activities_path(@user), class: 'btn btn-default btn-lg' %>

app/views/activities/index.html.erb
<%= link_to 'Neue Aktivität', new_user_activity_path(@user), class: 'btn btn-primary btn-lg' %><br /><br />

<h1>Meine Aktivitäten</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Aktivität</th>
      <th>Datum</th>
      <th class="text-center" nowrap>Öffentlich</th>
      <th style="width: 50px;"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= link_to truncate(activity.body, length: 50), [@user, activity] %></td>
        <td><%= l activity.created_at.to_date %></td>
        <td class="text-center" nowrap><%= activity.publish ? 'Ja' : 'Nein' %></td>
        <td class="text-center">
          <%= link_to [@user, activity], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/activities/new.html.erb
<h2>Neue Aktivität</h2>

<%= render 'form' %>

<%= link_to 'Zur Übersicht', user_activities_path(@user), class: 'btn btn-default btn-lg' %>

app/views/activities/show.html.erb
<p>
  <strong>Aktivität:</strong>
  <%= @activity.body %>
</p>

<p>
  <strong>Öffentlich:</strong>
  <%= @activity.publish ? 'Ja' : 'Nein' %>
</p>

<%= link_to 'Zur Übersicht', user_activities_path(@user), class:'btn btn-default btn-lg' %>
<%= link_to 'Bearbeiten', edit_user_activity_path(@user, @activity), class:'btn btn-warning btn-lg' %>