config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/show'

  get 'login',   to: 'sessions#new',     as: 'login'
  get 'signup',  to: 'users#new',        as: 'signup'
  get 'logout',  to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :users do
    resources :activities
    resources :milestones, :except => :show
    resources :goals, :except => :show do
      get 'starting_point'
      post 'starting_point' => 'milestones#starting_point'
    end
  end

  root 'dashboard#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authorize

  helper_method :current_user


  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favicons.html.erb
<%= favicon_link_tag '/icon.ico' %>
<%= favicon_link_tag '/icon/icon_16x16.png',   rel: 'apple-touch-icon', sizes: '16x16',   type: 'image/png'  %>
<%= favicon_link_tag '/icon/icon_32x32.png',   rel: 'apple-touch-icon', sizes: '32x32',   type: 'image/png'  %>
<%= favicon_link_tag '/icon/icon_128x128.png', rel: 'apple-touch-icon', sizes: '128x128', type: 'image/png'  %>
<%= favicon_link_tag '/icon/icon_256x256.png', rel: 'apple-touch-icon', sizes: '256x256', type: 'image/png'  %>
<%= favicon_link_tag '/icon/icon_512x512.png', rel: 'apple-touch-icon', sizes: '512x512', type: 'image/png'  %>
<%= favicon_link_tag '/icon/icon-57.png', rel: 'apple-touch-icon', sizes: '57x57', type: 'image/png'  %>
<%= favicon_link_tag '/icon/icon-60.png', rel: 'apple-touch-icon', sizes: '60x60', type: 'image/png'  %>
<%= favicon_link_tag '/icon/icon-76.png', rel: 'apple-touch-icon', sizes: '76x76', type: 'image/png'  %>

app/views/application/_messages.html.erb
<% if flash.to_a.size > 0 %>
  <div class="messages">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash#{name}" %>
    <% end %>
  </div>
<% end %>

app/views/application/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if current_user %>

          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_url %></li>
            <li><%= link_to 'Meilensteine', user_milestones_url(current_user) %></li>
            <li><%= link_to 'Meine Aktivitäten', user_activities_url(current_user) %></li>
            <li><%= link_to 'Meine Ziele', user_goals_url(current_user) %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Logout', logout_path %></li>
          </ul>

        <% else %>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Login', login_path %></li>
            <li><%= link_to 'Registrieren', signup_path %></li>
          </ul>

        <% end %>

      </div><!-- /.navbar-collapse -->



  </div><!-- /.container -->
</nav>